import { FolkMusicEntry } from "@/types/music";

export const SAMPLE_FOLK_ENTRIES: FolkMusicEntry[] = [
  {
    id: "1",
    title: "The Foggy Dew",
    artist: "Traditional Irish",
    region: "Western Europe",
    country: "Ireland",
    era: "19th Century",
    year: 1880,
    tags: ["ballad", "rebellion", "traditional"],
    description: "An iconic Irish ballad commemorating the 1916 Easter Rising, passed down through generations. Its haunting melody captures the spirit of Irish nationalism and the struggle for independence.",
    media: [],
  },
  {
    id: "2",
    title: "Raag Bhairavi",
    artist: "Traditional Indian Classical",
    region: "South Asia",
    country: "India",
    era: "Ancient",
    year: 500,
    tags: ["raga", "classical", "devotional"],
    description: "A morning raga from the Hindustani classical tradition, expressing devotion and serenity. This ancient musical form has been performed for over 1500 years in temples and courts across India.",
    media: [],
  },
  {
    id: "3",
    title: "Mbube",
    artist: "Solomon Linda",
    region: "Sub-Saharan Africa",
    country: "South Africa",
    era: "20th Century",
    year: 1939,
    tags: ["isicathamiya", "zulu", "choral"],
    description: "Originally recorded by Solomon Linda and the Evening Birds, this Zulu song became a global sensation. It showcases the rich vocal harmonies of South African musical traditions.",
    media: [],
  },
  {
    id: "4",
    title: "Resham Firiri",
    artist: "Traditional Nepali",
    region: "South Asia",
    country: "Nepal",
    era: "Traditional",
    year: 1950,
    tags: ["folk", "mountain", "celebration"],
    description: "A beloved Nepali folk song celebrating the beauty of silk and the mountains. Often performed at festivals and gatherings, it represents the joy and community spirit of Nepali culture.",
    media: [],
  },
  {
    id: "5",
    title: "Greensleeves",
    artist: "English Traditional",
    region: "Western Europe",
    country: "England",
    era: "16th Century",
    year: 1580,
    tags: ["ballad", "romance", "classical"],
    description: "A timeless English folk song, possibly composed during the reign of Elizabeth I. Its melancholic melody has been adapted countless times across genres and cultures.",
    media: [],
  },
];

export const REGIONS = [
  "All Regions",
  "Western Europe",
  "Eastern Europe",
  "South Asia",
  "East Asia",
  "Sub-Saharan Africa",
  "North Africa",
  "Middle East",
  "North America",
  "Central America",
  "South America",
  "Oceania",
];

export const ERAS = [
  "All Eras",
  "Ancient",
  "Medieval",
  "16th Century",
  "17th Century",
  "18th Century",
  "19th Century",
  "20th Century",
  "21st Century",
  "Traditional",
];

export const COMMON_TAGS = [
  "ballad",
  "traditional",
  "classical",
  "folk",
  "devotional",
  "celebration",
  "dance",
  "work song",
  "protest",
  "romance",
];
